### ISSUE TITLE
Long/Lat and comment for APRS-IS?

### ISSUE THREAD

**Issue by tubalainen** [cceremuga/pypacket#26]
I have read the readme.MD four times, still not 100% sure that I havnt missed how to configure my long/lat and comment string so that my APRS-rx igate shows up on the maps such as aprs.fi.

Have I missed the parameters or is it still to be implemented?

// SM4XDJ

**Comment by cceremuga** [comment]
Likely a miss in my implementation, I'll take a look thank you!

**Comment by bryanparke** [comment]
Glad to find this enhancement, I was so confused when my igate wasn't showing up on aprs.fi.  I'm switching from direwolf to pypacket and that is the only thing I couldn't get going.  Looking forward to it!

**Comment by cceremuga** [comment]
Thank you all for your patience!

The experimental v5 branch has support for this feature now. You'll need to add some more environment variables for lat/long (which can be done now with less struggle by renaming .env.example to .env and filling in values).

The beacon interval is configurable, defaulted to 10 minutes. Please let me know if you have any feedback. I'm going to run this on my raspberry pi for a few days to see if we've got something stable that I'd consider formally releasable. In my preliminary testing on my dev laptop, things showed up on the map as expected, so that's a good sign!

<img width="256" alt="Screen Shot 2020-05-30 at 7 29 16 AM" src="https://user-images.githubusercontent.com/525742/83327090-558e7a80-a247-11ea-88ca-9ffaaccc893d.png">

**Comment by ve7mhw** [comment]
That sounds great, I’ll give it a go soon. Thanks for all your hard work.

**Comment by cceremuga** [comment]
Something else worth considering, would we also like a user-customizable text comment on the beacons? I'd be happy to make something like that configurable if there's interest.

**Comment by Nodeswitch** [comment]
@cceremuga 

> 
> 
> Something else worth considering, would we also like a user-customizable text comment on the beacons? I'd be happy to make something like that configurable if there's interest.

I wouldn't say no to that feature! If not customisable text, possibly the option to change the APRS symbol associated with your call sign/SSID? Typically when using direwolf, I'll have `symbol="igate"` configured. It looks like [this is the spec](https://www.aprsdirect.com/symbol/list). 

The coordinate feature is working great, no issues encountered - thanks!

**Comment by cceremuga** [comment]
@Nodeswitch I can definitely manage that, I'll push up another commit before the v5 release with that included.

**Comment by cceremuga** [comment]
@Nodeswitch all set! Fetch and pull the latest from v5 and there's more options added to the config JSON for comment and symbol. Let me know how it works out for ya.

**Comment by bryanparke** [comment]
V5 is working great! Thank you! KM6YFK-10 is showing up!

**Comment by Nodeswitch** [comment]
@cceremuga Thanks! The default comment as per the config is appearing, but the symbol hasn't changed - still on TCP/IP. I've cleared the browser cache in case it was related to that.

**Comment by cceremuga** [comment]
I probably also should have read through the documentation more thoroughly, my bad 🤦 

http://www.aprs.org/symbols/symbolsX.txt

> 16 Jun 06: Suggest I for 2-way IGate and R overlay for RX only.

The underlying aprslib has the table hardcoded in the position class I'm extending, let me add a config option for that piece too as to make it more flexible.

**Comment by cceremuga** [comment]
Narrowed down the issue by taking a look at other IGates in my area, resolved!

<img width="246" alt="Screen Shot 2020-05-31 at 2 20 51 PM" src="https://user-images.githubusercontent.com/525742/83359705-fd8c6c80-a349-11ea-99c3-55e690648cb1.png">

**Comment by Nodeswitch** [comment]
@cceremuga Fantastic, thanks! Alternate symbol showing up fine with the update.

I'll run with this for a while and report back on anything. Obviously things are a bit quieter right now, so not picking up many transmissions as the before times to test against.

**Comment by cceremuga** [comment]
Closing this as completed, merging the v5 branch. I'll give it a few more days before tagging the release in case any bugs crop up.
