### ISSUE TITLE
SSID is not stripped from username

### ISSUE THREAD

**Issue by n8henrie** [cceremuga/pypacket#64]
**Describe the bug**

With the current implementation, if a user's SSID is included in the username, it is also included in the attempted login to AIS.

Unfortunately, I am unable to successfully transmit a packet, using aprslib directly, if I try to log in with an SSID attacked to my username.

**To Reproduce**

```python
import aprslib
IS = aprslib.IS("KI5AYO-0", passwd=12345)
IS.connect()
IS.sendall("KI5AYO-0>APDW15[REDACTED]\r\n")
```

If I replace `IS = aprslib.IS("KI5AYO-0", passwd=12345)` with `IS = aprslib.IS("KI5AYO", passwd=12345)`, it works fine.

**Expected behavior**

The login should be processed *without* the SSID, but subsequent calls to `aprslib`'s `.sendall` should *include* the SSID.

**System info (please complete the following information):**
 - OS: MacOS Catalina, Raspbian Buster
 - Python Version 3.8.5
 - PyPacket Version 5.0

PR incoming

**Comment by n8henrie** [comment]
Hmm, while this fixes my ability to submit received packets, it looks like my igate beacon is still getting posted as `KI5AYO` (instead of `KI5AYO-0`, which I have set as my username).

Perhaps this should just be a documentation PR that specifies that the username should not include an SSID?

Or perhaps that should already be assumed, and I'm just new around here. Regardless, thanks for a great looking library!

**Comment by cceremuga** [comment]
Thanks for looking into this. I'll pull your branch locally and give it a quick test, then merge once everything checks out!

**Comment by cceremuga** [comment]
In digging deeper into the APRS-IS documentation, the SSID is required for authentication purposes (aside from zero): http://www.aprs-is.net/connecting.aspx

> A SSID of zero is assumed if the callsign does not have a SSID; therefore never explicitly define -0 as a SSID.

I appreciate the PR, going to decline it for now as I'd like to keep it as close as possible to the spec and the documentation wasn't obvious initially.

**Comment by n8henrie** [comment]
From the link:

> (-SSID is optional but equates to zero if omitted, see below)

So that seems odd in the setting of this issue, right? Why would I be unable to log in with pypacket when I include an SSID, and only able to log in if I omit it?
